version: '3'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "8000:80"
    networks:
      - redmine-red
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  mysql-redmine:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    networks:
      - redmine-red
    environment:
      -  MYSQL_ROOT_PASSWORD= root
      -  MYSQL_USER= red
      -  MYSQL_PASSWORD= secret
      -  MYSQL_DATABASE= redmine
  redmine:
    image: redmine:4.0.4
    restart: always
    ports:
      - 3000:3000
    networks:
      - redmine-red
    environment:
      -  VIRTUAL_HOST=luigi.redmine.com
      -  VIRTUAL_PORT=3000
      -  REDMINE_DB_USERNAME= red
      -  REDMINE_DB_PASSWORD= secret
      -  REDMINE_DB_DATABASE= redmine  
networks:
  redmine-red:
    driver: bridge